version: "3.7"

services:
  
  backend:
    user: root
    image: node:16-alpine3.11
    restart: unless-stopped
    ports:
      - 3001:3001
    build: ./s2c-Backend/
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./s2c-Backend:/code
      - ../data:/code/data
      #- /mnt/hdd2/Sketch2Circuit/data:/code/data
    networks:
      - backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: s2c

  clientapp:
    user: root
    image: node:16-alpine3.11
    restart: unless-stopped
    ports:
      - 3000:3000
    build: ./s2c-clientapp/
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./s2c-clientapp:/code

  mysql:
    user: root
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./database:/databasefile
      - s2c-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: s2c
volumes:
  s2c-mysql-data:
networks:
  backend: