version: "3.7"

services:
  
  backend:
    image: node:16-alpine3.11
    ports:
      - 3001:3001
    build: 
      dockerfile: ./Dockerfile
      context: ./s2c-Backend
    command: sh -c "yarn install && yarn run start"
    volumes:
      - ./s2c-Backend:/code
    networks:
      - backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: s2c

  clientapp:
    image: node:16-alpine3.11
    ports:
      - 3000:3000
    build: 
      dockerfile: ./Dockerfile
      context: ./s2c-clientapp
    command: sh -c "yarn install && yarn run start"
    volumes:
      - ./s2c-clientapp:/code

  mysql:
    image: mysql:8.0
    networks:
      - backend
    volumes:
      - s2c-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: s2c

volumes:
  s2c-mysql-data:
networks:
  backend:




