version: "3.7"

services:

  backend:
    user: root
    image: node:16-alpine3.11
    restart: unless-stopped
    ports:
      - 3001:3001
    build: ./s2c-Backend
    command: sh -c "yarn install && yarn start"
    volumes:
      - /mnt/hdd2/Sketch2Circuit/data:/data
      - ./s2c-Backend:/code
    networks:
      - backend
    env_file:
      - backend.env
    depends_on:
      - mysql

  clientapp:
    user: root
    image: node:16-alpine3.11
    restart: unless-stopped
    ports:
      - 3000:3000
    build: ./s2c-clientapp
    command: sh -c "yarn install && yarn build && yarn serve -s build -l 3000"
    volumes:
      - ./s2c-clientapp:/code
    env_file:
      - clientapp.env
    depends_on:
      - backend

  mysql:
    user: root
    image: mysql:8.0
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - s2c-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: s2c
volumes:
  s2c-mysql-data:
networks:
  backend: