name: CI to Docker
runs-on: [self-hosted, linux, ARM64]
on:
  push:
    branches: [ master ]
jobs:
  s2c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose
        run: docker-compose -f docker-compose.yml up -d
