name: CI to Docker
on:
  push:
    branches: [ master-production ]
jobs:
  s2c:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Close old Containers
        run: docker-compose down
      - name: Docker compose
        run: docker-compose up -d
      - name: Check containers
        run: docker ps -a